### ISSUE TITLE
ModuleNotFoundError: No module named 'detextify.paddle_text_detector'; 'detextify' is not a package

### ISSUE THREAD

**Issue by jameswan** [iuliaturc/detextify#30]
Already did pip install detextify, but still saying module not there.

Requirement already satisfied: uc-micro-py in c:\users\james\anaconda3\envs\detextify\lib\site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify]>=2.0.0->gradio->visualdl->paddleocr<3.0.0.0,>=2.6.1.2->detextify) (1.0.1)
Requirement already satisfied: pycparser in c:\users\james\anaconda3\envs\detextify\lib\site-packages (from cffi>=1.12.2->gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->tritonclient[all]->visualdl->paddleocr<3.0.0.0,>=2.6.1.2->detextify) (2.21)

(detextify) C:\Users\James\Desktop\detextify>detextify.py "C:\Users\James\Desktop\MJ"
Traceback (most recent call last):
  File "C:\Users\James\Desktop\detextify\detextify.py", line 8, in <module>
    from detextify.paddle_text_detector import PaddleTextDetector
  File "C:\Users\James\Desktop\detextify\detextify.py", line 8, in <module>
    from detextify.paddle_text_detector import PaddleTextDetector
ModuleNotFoundError: No module named 'detextify.paddle_text_detector'; 'detextify' is not a package

**Comment by jameswan** [comment]
The fix was to rename my Python file to be something other than detextify.py ie detext.py

Then as I have GPUs, I installed:
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
pip install "tensorflow<2.11"
VERIFY GPU: python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
